import {MigrationInterface, QueryRunner} from "typeorm";

export class UserStatus21678532899454 implements MigrationInterface {
    name = 'UserStatus21678532899454'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_status" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP CONSTRAINT "PK_892a2061d6a04a7e2efe4c26d6f"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD CONSTRAINT "PK_573dd09f0c80f3018ce2cf98e37" PRIMARY KEY ("id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "is_active" SET DEFAULT 'true'`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP CONSTRAINT "PK_573dd09f0c80f3018ce2cf98e37"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD CONSTRAINT "PK_9bab6c49e02f517fd2efd6c1a91" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP CONSTRAINT "PK_9bab6c49e02f517fd2efd6c1a91"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD CONSTRAINT "PK_573dd09f0c80f3018ce2cf98e37" PRIMARY KEY ("user_id", "id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_status" DROP CONSTRAINT "PK_573dd09f0c80f3018ce2cf98e37"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD CONSTRAINT "PK_9bab6c49e02f517fd2efd6c1a91" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP CONSTRAINT "PK_9bab6c49e02f517fd2efd6c1a91"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD CONSTRAINT "PK_573dd09f0c80f3018ce2cf98e37" PRIMARY KEY ("id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "is_active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP CONSTRAINT "PK_573dd09f0c80f3018ce2cf98e37"`);
        await queryRunner.query(`ALTER TABLE "user_status" ADD CONSTRAINT "PK_892a2061d6a04a7e2efe4c26d6f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_status" DROP COLUMN "user_id"`);
    }

}
