import {MigrationInterface, QueryRunner} from "typeorm";

export class UserTablesCreation1679809732512 implements MigrationInterface {
    name = 'UserTablesCreation1679809732512'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_data" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "username" character varying NOT NULL, "email" character varying, "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "udpated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT 'true', CONSTRAINT "PK_73a2ae063ee34712f94b8248ced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "otp_value" character varying NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_data_id" integer, CONSTRAINT "REL_bb265292800b7c8c85111da8a6" UNIQUE ("user_data_id"), CONSTRAINT "PK_08f84ddf228d07703186f1f54c1" PRIMARY KEY ("id", "user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_current_status_enum" AS ENUM('call', 'instagram', 'whatsapp', 'text', 'star', 'unavailable')`);
        await queryRunner.query(`CREATE TABLE "user_status" ("current_status" "public"."user_status_current_status_enum", "created_at" TIMESTAMP NOT NULL DEFAULT now(), "udpated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" character varying NOT NULL, CONSTRAINT "PK_9bab6c49e02f517fd2efd6c1a91" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`ALTER TABLE "user_data" ALTER COLUMN "username" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_data" ALTER COLUMN "email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_data" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_auth" ADD CONSTRAINT "FK_bb265292800b7c8c85111da8a66" FOREIGN KEY ("user_data_id") REFERENCES "user_data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_auth" DROP CONSTRAINT "FK_bb265292800b7c8c85111da8a66"`);
        await queryRunner.query(`ALTER TABLE "user_data" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_data" ALTER COLUMN "email" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_data" ALTER COLUMN "username" SET NOT NULL`);
        await queryRunner.query(`DROP TABLE "user_status"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_current_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_auth"`);
        await queryRunner.query(`DROP TABLE "user_data"`);
    }

}
